name: "mutant"
on:
  push:
    paths:
      - '.github/workflows/mutant.yml'
  schedule:
    - cron: '0 1 * * *'
jobs:
  mutagen:
    name: Mutagen
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install mutmut
      - name: Kill all mutants!!
        run: |
          mutmut run
          mutmut results
          mutmut junitxml --suspicious-policy=failure --untested-policy=skipped