name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          architecture: x64
      - name: Install pypa/build
        run: python -m pip install build
      - name: Get the tagged version
        id: get_version
        env:
          GITHUB_REF: ${{ github.ref }}
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}
        shell: bash
      - name: Build a binary wheel and a source tarball
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: python -m build --sdist --wheel --outdir dist/
      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ steps.get_version.outputs.VERSION }}
          path: ./CHANGELOG.md
      - name: Create draft release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          release_name: Version v${{ steps.get_version.outputs.VERSION }}
          body: ${{ steps.changelog_reader.outputs.changes }}
          draft: true
          prerelease: endWith(steps.get_version.outputs.VERSION, 'rc')
          artifacts: "dist/*"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}